import React, { Component } from 'react';
import {
    Link
} from "react-router-dom";
export default class LongPage extends Component {

    render() {
        return (
            <>
              
                                <br />
                                Really
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                long
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                ...
                                <br />
                                content
                            
            </>
        );
    }
}